baseURL: "/"
languageCode: en
DefaultContentLanguage: en
title: Personal website for Xinyu
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
