 
  [[main]]
  name = "About Me"
  weight = 70
  identifier = "about"
  url = "/about/"
  
 
  #[[main]]
   #name = "Home"
    #identifier = "home"
   # weight = 100
    #url = "/"
  
   [[main]]
  name = "Research Highlights"
  weight = 200
  identifier = "Research Highlights"
  url = "/Research Highlights/"
  
   # [[main]]
  #name = "Projects"
  #weight = 300
  #identifier = "Projects"
  #url = "/Projects/"

  [[main]]
  name = "Teaching"
  weight = 400
  identifier = "Teaching"
  url = "/Teaching/"

  [[main]]
  name = "Blog"
  weight = 500
  identifier = "Blog"
  url = "/blog/"


